# templates/tls-secret.yaml
{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.selfSigned -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.ingress.tls.secretName -}}
{{- if $secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ index $secret.data "tls.crt" }}
  tls.key: {{ index $secret.data "tls.key" }}
{{- else -}}
{{- $cert := genSelfSignedCert .Values.ingress.host nil nil 3650 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- end }}